# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2019-10-12 13:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallery', '0003_auto_20191012_1604'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='author_profile',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='gallery.Profile'),
        ),
    ]
